<?php

namespace Codascii\TutoBundle\Repository;

/**
 * TutorielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorielRepository extends \Doctrine\ORM\EntityRepository
{
}
