codascii_tuto:
    resource: "@CodasciiTutoBundle/Resources/config/routing.yml"
    prefix:   /tutoriels

codascii_article:
    resource: "@CodasciiArticleBundle/Resources/config/routing.yml"
    prefix:   /article

codascii_core:
    resource: "@CodasciiCoreBundle/Resources/config/routing.yml"
    prefix:   /

