codascii_article_view:
    path:     /{id}
    defaults:
        _controller: CodasciiArticleBundle:Article:view
        id: 1
    requirements:
        id: \d+

codascii_article_add:
    path:     /add
    defaults:
        _controller: CodasciiArticleBundle:Article:add

codascii_article_edit:
    path:     /edit/{id}
    defaults:
        _controller: CodasciiArticleBundle:Article:edit
    requirements:
        id: \d+

codascii_article_delete:
    path:     /delete/{id}
    defaults:
        _controller: CodasciiArticleBundle:Article:delete
    requirements:
        id: \d+
